name: BedWarsStats
version: 1.0-SNAPSHOT
author: Simonsator
depends: [Clans]
depend: [Clans]
main: de.simonsator.bedwarsstatsrel.BedWarsStatMain
description: Provides stats for clans for BedWarsReloaded